org.gradle.jvmargs=-Xmx4096M
org.gradle.java.home=C:/Program Files/Java/jdk-17
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=20
# unityProjectPath=C:/Users/kirit/My project (5)
# unity.projectPath=C:/Users/kirit/My project (5)
unity.debugSymbolLevel=none
unity.buildToolsVersion=34.0.0
unity.minSdkVersion=30
unity.targetSdkVersion=34
unity.compileSdkVersion=34
unity.applicationId=com.lensmatch.mobile
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=1.0.0
unity.namespace=com.lensmatch.mobile
# unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.76f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
# unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.76f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
# unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.76f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
